version: 2


models:
  - name: stg_btc
    columns:
      - name: HASH_KEY
        tests:
          - not_null
          - unique

  - name: stg_btc_outputs
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('stg_btc_outputs_py')


  - name: whale_alert
    latest_version: 1
    config:
      contract:
        enforced: true
    columns:
      - name: output_address
        data_type: string
        data_tests:
          - assert_valid_btc_address
      - name: total_sent
        data_type: float
      - name: tx_count
        data_type: int
      - name: total_sent_usd
        data_type: float

    versions:
      - v: 1

      - v: 2
        columns:
          - include: all
            exclude: [total_sent_usd] 


exposures:

  - name: BTC_whale_alert
    label: BTC WHALE ALERT
    type: dashboard
    maturity: high
    url: https://datastudio.google.com/reporting/2f45e641-47af-4a64-9db0-3da54fe06b1b
    description: >
      WHALE_ALERT for BITCOIN 

    depends_on:
      - ref('whale_alert', v=1)

    owner:
      name: xudro